11 
    de.renew.gui.CPNDrawing 350 
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9322 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 479 1090 112 110 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9323 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 802 1085 112 110 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9324 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 1138 521 112 110 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9325 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 1162 1096 112 110 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9326 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 203 1112 89 87 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9327 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 1806 1121 109 98 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9328 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 1480 1103 102 107 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9329 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 358 1060 52 31 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9330 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 998 1061 73 39 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9331 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 657 1056 73 39 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9332 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 1162 763 73 39 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9333 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 1338 1043 52 31 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9334 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 1664 1089 44 25 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 9335 "FillColor" "Color" 255 255 255 255 2 1812 1151 1708 1110 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector REF 13   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 9336 "FillColor" "Color" 255 255 255 255 2 1664 1109 1579 1140 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 13  
            CH.ifa.draw.figures.ChopEllipseConnector REF 7   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 9337 "FillColor" "Color" 255 255 255 255 2 1265 1122 1339 1074 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 4  
            CH.ifa.draw.standard.ChopBoxConnector REF 12   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 9338 "FillColor" "Color" 255 255 255 255 2 1390 1073 1487 1131 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 12  
            CH.ifa.draw.figures.ChopEllipseConnector REF 7   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 9339 "FillColor" "Color" 255 255 255 255 2 586 1123 657 1091 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 10   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 9340 "FillColor" "Color" 255 255 255 255 2 730 1089 807 1121 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 10  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 9341 "FillColor" "Color" 255 255 255 255 2 911 1123 998 1092 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 9   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 9342 "FillColor" "Color" 255 255 255 255 2 1071 1094 1167 1132 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 9  
            CH.ifa.draw.figures.ChopEllipseConnector REF 4   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 9343 "FillColor" "Color" 255 255 255 255 2 1195 631 1198 763 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 3  
            CH.ifa.draw.standard.ChopBoxConnector REF 11   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 9344 "FillColor" "Color" 255 255 255 255 2 1199 802 1216 1097 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 11  
            CH.ifa.draw.figures.ChopEllipseConnector REF 4   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9345 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 595 1099 "anterior2" "SansSerif" 0 12 0 REF 34 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9346 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1731 1122 "posterior5" "SansSerif" 0 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9347 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 739 1097 "posterior2" "SansSerif" 0 12 0 REF 39 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9348 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1595 1116 "anterior5" "SansSerif" 0 12 0 REF 19 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9349 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1276 1090 "anterior4" "SansSerif" 0 12 0 REF 24 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9350 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1409 1094 "posterior4" "SansSerif" 0 12 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9351 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 928 1099 "anterior3" "SansSerif" 0 12 0 REF 44 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9352 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1090 1105 "posterior3" "SansSerif" 0 12 0 REF 49 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9353 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 64 64 64 255 608 1253 45 32 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9354 2 618 1253 569 1189 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 88  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9355 2 607 1330 624 1285 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 9766 593 1328 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 88   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9356 3 576 936 571 1010 549 1093 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9358 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 64 64 64 255 555 904 45 32 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9357 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 579 1195 "cell" "SansSerif" 0 12 0 REF 89 
            CH.ifa.draw.standard.OffsetLocator -5 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 102 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9359 3 566 936 502 1034 520 1093 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 102  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9360 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 306 1030 "anterior1:whosposterior(posterior1);\nposterior1:whosanterior(anterior1);" "SansSerif" 0 9 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator -2 -32 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9361 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1597 1061 "anterior5:whosposterior(posterior5);\nposterior5:whosanterior(anterior5);" "SansSerif" 0 10 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator -1 -26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9362 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 64 64 64 255 333 1240 45 32 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9363 2 338 1240 279 1185 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 118  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9364 2 320 1327 347 1272 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 9779 306 1325 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 118   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9365 2 140 936 229 1117 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9366 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 64 64 64 255 110 904 45 32 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   REF 132 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9367 3 145 936 206 1012 236 1115 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 132  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9368 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 64 64 64 255 774 799 45 32 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9369 2 799 831 849 1087 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 139  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9371 3 941 923 900 986 872 1088 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9373 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 64 64 64 255 930 891 45 32 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9372 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 810 933 "cell" "SansSerif" 0 12 0 REF 140 
            CH.ifa.draw.standard.OffsetLocator -5 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 148 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9374 3 951 923 942 1019 890 1096 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 148  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9375 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 911 1001 "cell" "SansSerif" 0 12 0 REF 153 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9376 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 64 64 64 255 1340 1169 45 32 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9377 3 1349 1169 1325 1141 1274 1147 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 161  
            CH.ifa.draw.figures.ChopEllipseConnector REF 4   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9378 2 1325 1245 1352 1201 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 9742 1310 1243 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 161   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9379 3 1085 942 1130 1012 1189 1105 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9380 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 64 64 64 255 1053 910 45 32 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector REF 4   REF 175 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9381 3 1089 942 1162 1026 1196 1102 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 175  
            CH.ifa.draw.figures.ChopEllipseConnector REF 4   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9382 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 64 64 64 255 1551 1011 45 32 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 6995 2 1568 1043 1547 1107 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 182  
            CH.ifa.draw.figures.ChopEllipseConnector REF 7   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9384 3 1310 952 1365 1022 1492 1125 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9385 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 64 64 64 255 1275 920 45 32 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector REF 7   REF 191 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9386 2 1314 952 1494 1122 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 191  
            CH.ifa.draw.figures.ChopEllipseConnector REF 7   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9387 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 64 64 64 255 1941 1218 45 32 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9388 2 1941 1220 1904 1198 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 198  
            CH.ifa.draw.figures.ChopEllipseConnector REF 6   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9389 2 1908 1283 1945 1250 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 9723 1890 1279 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 198   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9390 3 1782 964 1787 1041 1837 1127 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9391 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 64 64 64 255 1759 932 45 32 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector REF 6   REF 212 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9392 3 1786 964 1813 1050 1843 1125 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 212  
            CH.ifa.draw.figures.ChopEllipseConnector REF 6   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9393 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1782 1049 "sent_signal" "SansSerif" 0 12 0 REF 209 
            CH.ifa.draw.standard.OffsetLocator 4 12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9394 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 94 942 "cell:send(sent_signal);" "SansSerif" 0 12 0 REF 132 
            CH.ifa.draw.standard.OffsetLocator 23 30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9395 3 557 2484 90 1404 225 1192 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9412 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 541 2484 44 25 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9396 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 1665 2328 44 25 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9397 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 1818 2207 44 25 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9398 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 1821 2111 39 34 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9399 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1840 2120 "[]" "SansSerif" 0 12 0 REF 232 
            CH.ifa.draw.standard.OffsetLocator 4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9400 2 1840 2145 1840 2207 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 232  
            CH.ifa.draw.standard.ChopBoxConnector REF 231   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9401 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 1667 2202 39 34 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9402 2 1818 2219 1705 2219 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 231  
            CH.ifa.draw.figures.ChopEllipseConnector REF 240   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9403 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1744 2211 "states" "SansSerif" 0 12 0 REF 241 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9404 2 1686 2236 1686 2328 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 240  
            CH.ifa.draw.standard.ChopBoxConnector REF 230   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9405 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 1536 2478 39 34 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9406 2 1566 2482 1676 2353 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 253  
            CH.ifa.draw.standard.ChopBoxConnector REF 230   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9407 3 561 2484 400 1396 510 1194 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 228  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9408 3 564 2484 723 1397 833 1189 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 228  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9409 3 568 2484 1075 1381 1190 1198 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 228  
            CH.ifa.draw.figures.ChopEllipseConnector REF 4   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9410 4 576 2484 1275 1822 1400 1278 1494 1191 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 228  
            CH.ifa.draw.figures.ChopEllipseConnector REF 7   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9411 4 583 2484 1611 1870 1703 1279 1818 1200 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 228  
            CH.ifa.draw.figures.ChopEllipseConnector REF 6   REF 228 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9413 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 243 2450 "P3p: new VPC_CElegans_cell_building_blocks;\nP4p: new VPC_CElegans_cell_building_blocks;\nP5p: new VPC_CElegans_cell_building_blocks;\nP6p: new VPC_CElegans_cell_building_blocks;\nP7p: new VPC_CElegans_cell_building_blocks;\nP8p: new VPC_CElegans_cell_building_blocks;" "SansSerif" 0 12 0 REF 228 
            CH.ifa.draw.standard.OffsetLocator -196 5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9414 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1673 2282 "states" "SansSerif" 0 12 0 REF 248 
            CH.ifa.draw.standard.OffsetLocator 4 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9415 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 535 2561 39 34 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9416 2 556 2562 561 2509 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 284  
            CH.ifa.draw.standard.ChopBoxConnector REF 228   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9417 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 550 2570 "[]" "SansSerif" 0 12 0 REF 284 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9418 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1082 769 "dorsal:whosventral(ventral);\nventral:whosdorsal(dorsal);" "SansSerif" 0 10 0 REF 11 
            CH.ifa.draw.standard.OffsetLocator -49 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9419 2 285 1134 358 1090 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector REF 8   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9420 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 295 1104 "anterior1" "SansSerif" 0 12 0 REF 295 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9421 2 410 1087 485 1123 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 8  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9422 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 418 1097 "posterior1" "SansSerif" 0 12 0 REF 303 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9423 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 1174 360 44 25 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9424 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 1177 247 39 34 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9425 2 1196 281 1196 360 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 312  
            CH.ifa.draw.standard.ChopBoxConnector REF 311   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9426 2 1195 385 1195 522 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 311  
            CH.ifa.draw.figures.ChopEllipseConnector REF 3   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9427 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1187 445 "AC" "SansSerif" 0 12 0 REF 317 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9428 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1798 2247 "states: new VPC_CElegans_states_landscape" "SansSerif" 0 12 0 REF 231 
            CH.ifa.draw.standard.OffsetLocator 81 36 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9429 2 585 2496 1537 2495 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 228  
            CH.ifa.draw.figures.ChopEllipseConnector REF 253   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9430 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1001 2482 "[P3p, P4p, P5p, P6p, P7p, P8p]" "SansSerif" 0 12 0 REF 327 
            CH.ifa.draw.standard.OffsetLocator 22 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9431 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1539 2409 "[P3p, P4p, P5p, P6p, P7p, P8p]" "SansSerif" 0 12 0 REF 254 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9432 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1630 2332 "states:sync_states([P3p, P4p, P5p, P6p, P7p, P8p]);" "SansSerif" 0 12 0 REF 230 
            CH.ifa.draw.standard.OffsetLocator 81 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9433 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 198 997 "cell" "SansSerif" 0 12 0 REF 134 
            CH.ifa.draw.standard.OffsetLocator 17 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9434 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 143 1015 "sent_signal" "SansSerif" 0 12 0 REF 129 
            CH.ifa.draw.standard.OffsetLocator -10 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9435 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 276 1287 "signal_to_be_received" "SansSerif" 0 12 0 REF 124 
            CH.ifa.draw.standard.OffsetLocator 3 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9437 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 289 1249 "cell:receive(signal_to_be_received);" "SansSerif" 0 12 0 REF 118 
            CH.ifa.draw.standard.OffsetLocator 31 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9438 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 511 912 "cell:send(sent_signal);" "SansSerif" 0 12 0 REF 102 
            CH.ifa.draw.standard.OffsetLocator -5 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9439 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 528 1010 "sent_signal" "SansSerif" 0 12 0 REF 99 
            CH.ifa.draw.standard.OffsetLocator -3 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9440 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 520 999 "cell" "SansSerif" 0 12 0 REF 107 
            CH.ifa.draw.standard.OffsetLocator -5 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9442 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 851 964 "sent_signal" "SansSerif" 0 12 0 REF 145 
            CH.ifa.draw.standard.OffsetLocator -24 -33 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9443 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 892 894 "cell:send(sent_signal);" "SansSerif" 0 12 0 REF 148 
            CH.ifa.draw.standard.OffsetLocator 1 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9444 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 611 1028 "anterior2:whosposterior(posterior2);\nposterior2:whosanterior(anterior2);" "SansSerif" 0 10 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator 6 -33 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9445 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 695 807 "cell:receive(signal_to_be_received);" "SansSerif" 0 12 0 REF 139 
            CH.ifa.draw.standard.OffsetLocator -4 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9447 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1017 920 "cell:send(sent_signal);" "SansSerif" 0 12 0 REF 175 
            CH.ifa.draw.standard.OffsetLocator 3 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9448 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1288 1176 "cell:receive(signal_to_be_received);" "SansSerif" 0 12 0 REF 161 
            CH.ifa.draw.standard.OffsetLocator 23 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9449 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1153 1018 "cell" "SansSerif" 0 12 0 REF 177 
            CH.ifa.draw.standard.OffsetLocator 20 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9450 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1077 989 "sent_signal" "SansSerif" 0 12 0 REF 172 
            CH.ifa.draw.standard.OffsetLocator -29 -26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9452 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 929 1058 "anterior3:whosposterior(posterior3);\nposterior3:whosanterior(anterior3);" "SansSerif" 0 10 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator -17 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9454 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1373 993 "sent_signal" "SansSerif" 0 12 0 REF 188 
            CH.ifa.draw.standard.OffsetLocator 3 -37 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9455 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1396 1021 "cell" "SansSerif" 0 12 0 REF 193 
            CH.ifa.draw.standard.OffsetLocator 1 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9456 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1218 923 "cell:send(sent_signal);" "SansSerif" 0 12 0 REF 191 
            CH.ifa.draw.standard.OffsetLocator -18 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9457 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1441 1015 "cell:receive(signal_to_be_received);" "SansSerif" 0 12 0 REF 182 
            CH.ifa.draw.standard.OffsetLocator -35 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9459 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1244 1041 "anterior4:whosposterior(posterior4);\nposterior4:whosanterior(anterior4);" "SansSerif" 0 10 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator -32 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9462 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1714 939 "cell:send(sent_signal);" "SansSerif" 0 12 0 REF 212 
            CH.ifa.draw.standard.OffsetLocator -6 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9463 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1797 1018 "cell" "SansSerif" 0 12 0 REF 214 
            CH.ifa.draw.standard.OffsetLocator -8 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9466 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 805 1443 112 110 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9467 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 491 1457 112 110 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9468 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 199 1450 112 110 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9469 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 1796 1415 112 110 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9470 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 1476 1435 112 110 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9471 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 1166 1442 112 110 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9472 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 299 1902 "P3p" "SansSerif" 0 12 0 REF 225 
            CH.ifa.draw.standard.OffsetLocator -14 72 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9473 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 464 1898 "P4p" "SansSerif" 0 12 0 REF 258 
            CH.ifa.draw.standard.OffsetLocator -6 67 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9474 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 593 1909 "P5p" "SansSerif" 0 12 0 REF 262 
            CH.ifa.draw.standard.OffsetLocator -95 81 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9475 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 804 1876 "P6p" "SansSerif" 0 12 0 REF 266 
            CH.ifa.draw.standard.OffsetLocator -65 43 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9476 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1609 1836 "P8p" "SansSerif" 0 12 0 REF 274 
            CH.ifa.draw.standard.OffsetLocator 419 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9486 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1236 333 "AC: new VPC_CElegans_ac;" "SansSerif" 0 12 0 REF 311 
            CH.ifa.draw.standard.OffsetLocator 114 -31 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9488 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 64 64 64 255 138 1737 45 32 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9489 2 166 1737 236 1556 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 433  
            CH.ifa.draw.figures.ChopEllipseConnector REF 411   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9490 3 261 1560 266 1614 172 1737 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 411  
            CH.ifa.draw.standard.ChopBoxConnector REF 433   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9494 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 98 1739 "cell:receive(signal_to_be_received);" "SansSerif" 0 12 0 REF 433 
            CH.ifa.draw.standard.OffsetLocator 35 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9496 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 215 1588 "cell" "SansSerif" 0 12 0 REF 434 
            CH.ifa.draw.standard.OffsetLocator 23 -50 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9499 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 213 1642 "signal_to_be_received" "SansSerif" 0 12 0 REF 439 
            CH.ifa.draw.standard.OffsetLocator 54 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9500 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 64 64 64 255 451 1773 45 32 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9501 2 477 1773 534 1565 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 452  
            CH.ifa.draw.figures.ChopEllipseConnector REF 410   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9502 3 543 1567 528 1738 490 1773 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 410  
            CH.ifa.draw.standard.ChopBoxConnector REF 452   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9506 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 411 1775 "cell:receive(signal_to_be_received);" "SansSerif" 0 12 0 REF 452 
            CH.ifa.draw.standard.OffsetLocator 35 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9507 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 519 1611 "cell" "SansSerif" 0 12 0 REF 453 
            CH.ifa.draw.standard.OffsetLocator 23 -50 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9510 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 510 1664 "signal_to_be_received" "SansSerif" 0 12 0 REF 458 
            CH.ifa.draw.standard.OffsetLocator 54 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9511 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 64 64 64 255 687 1853 45 32 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9512 2 716 1853 841 1549 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 471  
            CH.ifa.draw.figures.ChopEllipseConnector REF 409   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9513 3 851 1552 815 1730 721 1853 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 409  
            CH.ifa.draw.standard.ChopBoxConnector REF 471   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9517 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 647 1855 "cell:receive(signal_to_be_received);" "SansSerif" 0 12 0 REF 471 
            CH.ifa.draw.standard.OffsetLocator 35 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9519 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 792 1643 "cell" "SansSerif" 0 12 0 REF 472 
            CH.ifa.draw.standard.OffsetLocator 23 -50 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9522 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 780 1696 "signal_to_be_received" "SansSerif" 0 12 0 REF 477 
            CH.ifa.draw.standard.OffsetLocator 54 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9523 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 64 64 64 255 1048 1856 45 32 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9524 2 1076 1856 1202 1548 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 490  
            CH.ifa.draw.figures.ChopEllipseConnector REF 414   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9525 3 1212 1551 1176 1733 1082 1856 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 414  
            CH.ifa.draw.standard.ChopBoxConnector REF 490   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9529 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1008 1858 "cell:receive(signal_to_be_received);" "SansSerif" 0 12 0 REF 490 
            CH.ifa.draw.standard.OffsetLocator 35 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9531 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1153 1644 "cell" "SansSerif" 0 12 0 REF 491 
            CH.ifa.draw.standard.OffsetLocator 23 -50 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9534 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1141 1697 "signal_to_be_received" "SansSerif" 0 12 0 REF 496 
            CH.ifa.draw.standard.OffsetLocator 54 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9535 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 64 64 64 255 1365 1869 45 32 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9536 2 1393 1869 1514 1542 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 509  
            CH.ifa.draw.figures.ChopEllipseConnector REF 413   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9537 3 1525 1544 1493 1746 1399 1869 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 413  
            CH.ifa.draw.standard.ChopBoxConnector REF 509   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9540 2 1607 1343 1557 1442 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9635 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1600 1327 24 16 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector REF 413   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9541 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1325 1871 "cell:receive(signal_to_be_received);" "SansSerif" 0 12 0 REF 509 
            CH.ifa.draw.standard.OffsetLocator 35 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9543 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1467 1647 "cell" "SansSerif" 0 12 0 REF 510 
            CH.ifa.draw.standard.OffsetLocator 23 -50 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9546 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1456 1700 "signal_to_be_received" "SansSerif" 0 12 0 REF 515 
            CH.ifa.draw.standard.OffsetLocator 54 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9547 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 64 64 64 255 1745 1735 45 32 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9548 2 1772 1735 1837 1523 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 534  
            CH.ifa.draw.figures.ChopEllipseConnector REF 412   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9549 3 1843 1524 1808 1712 1784 1735 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 412  
            CH.ifa.draw.standard.ChopBoxConnector REF 534   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9552 2 1897 1368 1874 1421 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 9638 1889 1352 24 16 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector REF 412   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9553 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1705 1737 "cell:receive(signal_to_be_received);" "SansSerif" 0 12 0 REF 534 
            CH.ifa.draw.standard.OffsetLocator 35 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9555 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1818 1571 "cell" "SansSerif" 0 12 0 REF 535 
            CH.ifa.draw.standard.OffsetLocator 23 -50 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9558 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1807 1623 "signal_to_be_received" "SansSerif" 0 12 0 REF 540 
            CH.ifa.draw.standard.OffsetLocator 54 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9560 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1073 2008 "P7p" "SansSerif" 0 12 0 REF 270 
            CH.ifa.draw.standard.OffsetLocator 48 179 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9561 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 170 1337 73 39 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9562 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 444 1339 73 39 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9563 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 364 1345 "dorsal:whosventral(ventral);\nventral:whosdorsal(dorsal);" "SansSerif" 0 10 0 REF 563 
            CH.ifa.draw.standard.OffsetLocator -49 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9564 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 786 1328 73 39 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9565 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 706 1334 "dorsal:whosventral(ventral);\nventral:whosdorsal(dorsal);" "SansSerif" 0 10 0 REF 567 
            CH.ifa.draw.standard.OffsetLocator -49 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9566 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 1138 1343 73 39 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9567 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 1459 1310 73 39 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9568 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 1775 1307 73 39 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9569 2 239 1197 210 1337 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector REF 562   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9570 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 73 1346 "dorsal:whosventral(ventral);\nventral:whosdorsal(dorsal);" "SansSerif" 0 10 0 REF 562 
            CH.ifa.draw.standard.OffsetLocator -66 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9571 2 212 1376 239 1454 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 562  
            CH.ifa.draw.figures.ChopEllipseConnector REF 411   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9572 2 522 1198 485 1339 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 563   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9573 2 488 1378 526 1462 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 563  
            CH.ifa.draw.figures.ChopEllipseConnector REF 410   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9574 2 850 1194 825 1328 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 567   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9575 2 827 1367 848 1446 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 567  
            CH.ifa.draw.figures.ChopEllipseConnector REF 409   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9576 2 1208 1205 1178 1343 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 4  
            CH.ifa.draw.standard.ChopBoxConnector REF 571   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9577 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1028 1346 "dorsal:whosventral(ventral);\nventral:whosdorsal(dorsal);" "SansSerif" 0 10 0 REF 571 
            CH.ifa.draw.standard.OffsetLocator -79 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9578 2 1181 1382 1205 1446 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 571  
            CH.ifa.draw.figures.ChopEllipseConnector REF 414   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9579 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1341 1311 "dorsal:whosventral(ventral);\nventral:whosdorsal(dorsal);" "SansSerif" 0 10 0 REF 572 
            CH.ifa.draw.standard.OffsetLocator -87 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9580 2 1521 1208 1499 1310 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 7  
            CH.ifa.draw.standard.ChopBoxConnector REF 572   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9581 2 1499 1349 1521 1437 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 572  
            CH.ifa.draw.figures.ChopEllipseConnector REF 413   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9582 2 1846 1217 1817 1307 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector REF 573   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9583 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1688 1304 "dorsal:whosventral(ventral);\nventral:whosdorsal(dorsal);" "SansSerif" 0 10 0 REF 573 
            CH.ifa.draw.standard.OffsetLocator -56 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9584 2 1817 1346 1838 1418 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 573  
            CH.ifa.draw.figures.ChopEllipseConnector REF 412   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9585 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 205 1259 "ventral" "SansSerif" 0 12 0 REF 574 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9586 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 484 1260 "ventral" "SansSerif" 0 12 0 REF 587 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9587 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 818 1253 "ventral" "SansSerif" 0 12 0 REF 597 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9588 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1174 1266 "ventral" "SansSerif" 0 12 0 REF 607 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9589 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1491 1251 "ventral" "SansSerif" 0 12 0 REF 623 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9590 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1812 1254 "ventral" "SansSerif" 0 12 0 REF 633 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9591 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1189 907 "dorsal" "SansSerif" 0 12 0 REF 59 
            CH.ifa.draw.standard.OffsetLocator -1 -34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9592 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 208 1407 "dorsal" "SansSerif" 0 12 0 REF 582 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9593 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 490 1412 "dorsal" "SansSerif" 0 12 0 REF 592 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9594 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 820 1398 "dorsal" "SansSerif" 0 12 0 REF 602 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9595 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1176 1406 "dorsal" "SansSerif" 0 12 0 REF 615 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9596 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1493 1385 "dorsal" "SansSerif" 0 12 0 REF 628 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9597 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1810 1374 "dorsal" "SansSerif" 0 12 0 REF 641 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9598 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 140 2009 44 25 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9599 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 255 255 255 63 2006 39 34 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9600 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 78 2015 "[]" "SansSerif" 0 12 0 REF 686 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9601 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 58 2052 "hyp7_1: new VPC_CElegans_hyp7;\nhyp7_2: new VPC_CElegans_hyp7;\nhyp7_3: new VPC_CElegans_hyp7;\nhyp7_4: new VPC_CElegans_hyp7;\nhyp7_5: new VPC_CElegans_hyp7;\nhyp7_6: new VPC_CElegans_hyp7;" "SansSerif" 0 12 0 REF 685 
            CH.ifa.draw.standard.OffsetLocator -12 82 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9602 2 101 2023 140 2022 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 686  
            CH.ifa.draw.standard.ChopBoxConnector REF 685   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9603 3 158 2009 24 1563 202 1519 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 685  
            CH.ifa.draw.figures.ChopEllipseConnector REF 411   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9604 3 168 2009 377 1626 502 1543 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 685  
            CH.ifa.draw.figures.ChopEllipseConnector REF 410   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9605 4 182 2009 632 1737 719 1591 815 1529 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 685  
            CH.ifa.draw.figures.ChopEllipseConnector REF 409   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9606 4 184 2018 835 1940 987 1651 1176 1528 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 685  
            CH.ifa.draw.figures.ChopEllipseConnector REF 414   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9607 4 184 2019 1068 1950 1328 1696 1494 1529 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 685  
            CH.ifa.draw.figures.ChopEllipseConnector REF 413   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9608 4 184 2021 1522 2022 1611 1590 1803 1495 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 685  
            CH.ifa.draw.figures.ChopEllipseConnector REF 412   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9609 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 114 1904 "hyp7_1" "SansSerif" 0 12 0 REF 697 
            CH.ifa.draw.standard.OffsetLocator 20 148 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9610 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 201 1901 "hyp7_2" "SansSerif" 0 12 0 REF 701 
            CH.ifa.draw.standard.OffsetLocator -115 133 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9611 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 234 1961 "hyp7_3" "SansSerif" 0 12 0 REF 705 
            CH.ifa.draw.standard.OffsetLocator -245 200 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9612 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 828 1921 "hyp7_4" "SansSerif" 0 12 0 REF 709 
            CH.ifa.draw.standard.OffsetLocator 167 156 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9613 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1044 1937 "hyp7_5" "SansSerif" 0 12 0 REF 713 
            CH.ifa.draw.standard.OffsetLocator 224 171 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9614 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1257 2014 "hyp7_6" "SansSerif" 0 12 0 REF 717 
            CH.ifa.draw.standard.OffsetLocator 283 264 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9616 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 888 642 24 16 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9619 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1549 742 24 16 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9623 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 290 1392 24 16 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9632 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1248 1299 24 16 NULL  REF 523 REF 548 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9652 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 709 549 37 23 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9653 3 737 572 754 591 737 625 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 743  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9654 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 722 623 20 20 NULL    REF 748 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9655 3 728 625 710 596 722 572 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 748  
            CH.ifa.draw.standard.ChopBoxConnector REF 743   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9656 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 175 175 255 736 590 "t+1" "SansSerif" 0 12 0 REF 744 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9657 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 175 175 255 709 591 "t" "SansSerif" 0 12 0 REF 749 
            CH.ifa.draw.standard.OffsetLocator -8 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9658 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 729 625 "0" "SansSerif" 0 12 0 REF 748 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9659 3 741 631 858 591 894 642 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 748  
            CH.ifa.draw.standard.ChopBoxConnector REF 739   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9660 3 888 654 834 673 741 637 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 739  
            CH.ifa.draw.figures.ChopEllipseConnector REF 748   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9661 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 822 694 "t" "SansSerif" 0 12 0 REF 766 
            CH.ifa.draw.standard.OffsetLocator 10 47 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9662 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 831 582 "t" "SansSerif" 0 12 0 REF 762 
            CH.ifa.draw.standard.OffsetLocator 16 -26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9663 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 1589 481 37 23 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9664 3 1617 504 1634 523 1617 557 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 776  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9665 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 1602 555 20 20 NULL    REF 781 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9666 3 1608 557 1590 528 1602 504 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 781  
            CH.ifa.draw.standard.ChopBoxConnector REF 776   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9667 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 175 175 255 1616 522 "t+1" "SansSerif" 0 12 0 REF 777 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9668 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 175 175 255 1589 523 "t" "SansSerif" 0 12 0 REF 782 
            CH.ifa.draw.standard.OffsetLocator -8 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9669 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1609 557 "0" "SansSerif" 0 12 0 REF 781 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9670 3 1607 573 1554 648 1560 742 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 781  
            CH.ifa.draw.standard.ChopBoxConnector REF 740   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9671 3 1565 742 1613 658 1612 575 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 740  
            CH.ifa.draw.figures.ChopEllipseConnector REF 781   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9672 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1597 697 "t" "SansSerif" 0 12 0 REF 799 
            CH.ifa.draw.standard.OffsetLocator 10 47 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9673 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1594 623 "t" "SansSerif" 0 12 0 REF 795 
            CH.ifa.draw.standard.OffsetLocator 16 -26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9674 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1602 746 "guard t>90" "SansSerif" 0 12 0 REF 740 
            CH.ifa.draw.standard.OffsetLocator 71 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9675 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1192 256 "[]" "SansSerif" 0 12 0 REF 312 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 9693 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1981 1428 "Hyp7" "SansSerif" 1 41 0 NULL NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9699 2 912 646 1141 590 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 739  
            CH.ifa.draw.figures.ChopEllipseConnector REF 3   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9700 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1017 610 "cell" "SansSerif" 0 12 0 REF 816 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9701 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 819 631 "guard t>90" "SansSerif" 0 12 0 REF 739 
            CH.ifa.draw.standard.OffsetLocator -51 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9702 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 934 646 "cell:send(sent_signal);" "SansSerif" 0 12 0 REF 739 
            CH.ifa.draw.standard.OffsetLocator 95 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9703 2 895 658 865 720 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 739  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 9704 850 718 20 20 NULL    REF 834 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9706 2 855 736 808 799 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 834  
            CH.ifa.draw.standard.ChopBoxConnector REF 139   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9709 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1409 743 "cell:send(sent_signal);" "SansSerif" 0 12 0 REF 740 
            CH.ifa.draw.standard.OffsetLocator -91 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9710 2 1561 758 1562 860 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 740  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 9711 1552 859 20 20 NULL    REF 846 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9712 2 1563 879 1572 1011 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 846  
            CH.ifa.draw.standard.ChopBoxConnector REF 182   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9713 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1507 937 "signal_to_be_received" "SansSerif" 0 12 0 REF 847 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9715 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1180 659 "ventral" "SansSerif" 0 12 0 REF 54 
            CH.ifa.draw.standard.OffsetLocator 3 -30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9705 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 859 681 "sent_signal" "SansSerif" 0 12 0 REF 830 
            CH.ifa.draw.standard.OffsetLocator 10 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9708 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 777 755 "signal_to_be_received" "SansSerif" 0 12 0 REF 835 
            CH.ifa.draw.standard.OffsetLocator 6 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9720 2 1244 600 1549 744 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 3  
            CH.ifa.draw.standard.ChopBoxConnector REF 740   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9721 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1387 664 "cell" "SansSerif" 0 12 0 REF 863 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9458 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1550 1059 "cell" "SansSerif" 0 12 0 REF 183 
            CH.ifa.draw.standard.OffsetLocator 2 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9722 2 1900 1352 1900 1299 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 548  
            CH.ifa.draw.figures.ChopEllipseConnector REF 207   REF 207 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9724 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1530 801 "sent_signal" "SansSerif" 0 12 0 REF 842 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9464 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1910 1200 "cell" "SansSerif" 0 12 0 REF 199 
            CH.ifa.draw.standard.OffsetLocator -3 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9465 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1889 1254 "signal_to_be_received" "SansSerif" 0 12 0 REF 204 
            CH.ifa.draw.standard.OffsetLocator 23 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9544 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1575 1370 "hyp7" "SansSerif" 0 12 0 REF 519 
            CH.ifa.draw.standard.OffsetLocator 6 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9727 2 1611 1327 1611 1280 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 523  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 9728 1601 1260 20 20 NULL    REF 894 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9729 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 64 64 64 255 1631 1195 45 32 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9731 2 1617 1263 1642 1227 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 894  
            CH.ifa.draw.standard.ChopBoxConnector REF 895   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9732 2 1578 1177 1631 1200 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 7  
            CH.ifa.draw.standard.ChopBoxConnector REF 895   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9733 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1595 1180 "cell" "SansSerif" 0 12 0 REF 900 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9734 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1569 1237 "signal_to_be_received" "SansSerif" 0 12 0 REF 896 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9735 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1580 1295 "sent_signal" "SansSerif" 0 12 0 REF 890 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9725 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1872 1320 "sent_signal" "SansSerif" 0 12 0 REF 874 
            CH.ifa.draw.standard.OffsetLocator 3 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9726 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1859 1352 "hyp7:send(sent_signal);" "SansSerif" 0 12 0 REF 548 
            CH.ifa.draw.standard.OffsetLocator 23 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9461 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1862 1224 "cell:receive(signal_to_be_received);" "SansSerif" 0 12 0 REF 198 
            CH.ifa.draw.standard.OffsetLocator -4 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 9689 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1828 1137 "P8p" "SansSerif" 1 41 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 9688 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1496 1128 "P7p" "SansSerif" 1 41 0 NULL NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9542 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1544 1335 "hyp7:send(sent_signal);" "SansSerif" 0 12 0 REF 523 
            CH.ifa.draw.standard.OffsetLocator -3 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9730 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 1558 1205 "cell:receive(signal_to_be_received);" "SansSerif" 0 12 0 REF 895 
            CH.ifa.draw.standard.OffsetLocator 2 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 9687 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1182 1121 "P6p" "SansSerif" 1 41 0 NULL NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9453 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1313 1136 "cell" "SansSerif" 0 12 0 REF 162 
            CH.ifa.draw.standard.OffsetLocator 11 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9736 2 1233 1444 1258 1315 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 414  
            CH.ifa.draw.standard.ChopBoxConnector REF 742   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9737 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1232 1371 "hyp7" "SansSerif" 0 12 0 REF 935 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9556 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1879 1381 "hyp7" "SansSerif" 0 12 0 REF 544 
            CH.ifa.draw.standard.OffsetLocator 7 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9741 2 1268 1299 1314 1260 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 742  
            CH.ifa.draw.figures.ChopEllipseConnector REF 170   REF 170 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9744 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1260 1271 "sent_signal" "SansSerif" 0 12 0 REF 946 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9451 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1271 1214 "signal_to_be_received" "SansSerif" 0 12 0 REF 167 
            CH.ifa.draw.standard.OffsetLocator -7 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9740 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1197 1298 "hyp7:send(sent_signal);" "SansSerif" 0 12 0 REF 742 
            CH.ifa.draw.standard.OffsetLocator 2 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 9745 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 64 64 64 255 969 1196 45 32 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9747 2 887 1451 923 1383 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 409  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 9754 916 1367 24 16 NULL    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9748 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 892 1409 "hyp7" "SansSerif" 0 12 0 REF 960 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 9686 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 822 1110 "P5p" "SansSerif" 1 41 0 NULL NULL  REF 965 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9755 2 933 1367 976 1311 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 965  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 9756 971 1293 20 20 NULL    REF 974 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9757 2 982 1294 989 1228 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 974  
            CH.ifa.draw.standard.ChopBoxConnector REF 959   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9758 2 907 1167 969 1199 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 2  
            CH.ifa.draw.standard.ChopBoxConnector REF 959   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9759 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 929 1175 "cell" "SansSerif" 0 12 0 REF 979 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9760 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 925 1253 "signal_to_be_received" "SansSerif" 0 12 0 REF 975 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9761 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 923 1331 "sent_signal" "SansSerif" 0 12 0 REF 970 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9746 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 901 1203 "cell:receive(signal_to_be_received);" "SansSerif" 0 12 0 REF 959 
            CH.ifa.draw.standard.OffsetLocator 7 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 9763 592 1402 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9765 2 603 1402 603 1348 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 996  
            CH.ifa.draw.figures.ChopEllipseConnector REF 97   REF 97 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9681 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 553 1298 "signal_to_be_received" "SansSerif" 0 12 0 REF 94 
            CH.ifa.draw.standard.OffsetLocator -2 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9441 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 255 255 255 547 1259 "cell:receive(signal_to_be_received);" "SansSerif" 0 12 0 REF 88 
            CH.ifa.draw.standard.OffsetLocator 14 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9768 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 572 1367 "sent_signal" "SansSerif" 0 12 0 REF 997 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9773 2 574 1465 599 1418 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 410  
            CH.ifa.draw.standard.ChopBoxConnector REF 996   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9774 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 573 1433 "hyp7" "SansSerif" 0 12 0 REF 1010 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9764 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 542 1405 "hyp7:send(sent_signal);" "SansSerif" 0 12 0 REF 996 
            CH.ifa.draw.standard.OffsetLocator 3 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 9685 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 496 1120 "P4p" "SansSerif" 1 41 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 0 "FigureWithID" "Int" 9684 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 214 1127 "P3p" "SansSerif" 1 41 0 NULL NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9775 2 278 1456 298 1408 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 411  
            CH.ifa.draw.standard.ChopBoxConnector REF 741   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9776 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 275 1424 "hyp7" "SansSerif" 0 12 0 REF 1023 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 9778 2 303 1392 315 1345 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 741  
            CH.ifa.draw.figures.ChopEllipseConnector REF 127   REF 127 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9436 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 299 1202 "cell" "SansSerif" 0 12 0 REF 119 
            CH.ifa.draw.standard.OffsetLocator 0 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9777 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 246 1390 "hyp7:send(sent_signal);" "SansSerif" 0 12 0 REF 741 
            CH.ifa.draw.standard.OffsetLocator 9 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9780 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 278 1360 "sent_signal" "SansSerif" 0 12 0 REF 1031 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9762 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 874 1367 "hyp7:send(sent_signal);" "SansSerif" 0 12 0 REF 965 
            CH.ifa.draw.standard.OffsetLocator 11 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  0 0 1920 1044 